apiVersion: v1
kind: Service
metadata:
  name: clean-architecture-spring-boot-gradle
  namespace: reactive
spec:
  selector:
    app: clean-architecture-spring-boot-gradle
  ports:
    - name: default
      protocol: TCP
      port: 80
      targetPort: 8080
